// Receipt status
export enum ReceiptStatus {
  GENERATED = 'generated',
  SENT = 'sent',
  DOWNLOADED = 'downloaded'
}

// Receipt model for generated receipts
export interface Receipt {
  id: string; // UUID
  receiptNumber: string; // Auto-generated unique number (e.g., "RNT-2025-001")

  // Associated entities
  propertyId: string; // UUID reference to properties table
  rentTransactionId?: string; // UUID reference to rent_transactions table
  tenantId?: string; // UUID reference to tenants table

  // Receipt details
  receiptDate: Date;
  amount: number;
  description: string;

  // Receipt content (JSON structure for PDF generation)
  receiptData: ReceiptData;

  // File details
  pdfUrl?: string; // URL to generated PDF
  fileSize?: number; // PDF file size in bytes

  // Status and tracking
  status: ReceiptStatus;
  generatedBy: string; // UUID reference to users table
  sentTo?: string; // Email address if sent
  sentAt?: Date;

  // Metadata
  createdAt: Date;
  updatedAt: Date;
}

// Receipt data structure for PDF generation
export interface ReceiptData {
  // Property information
  property: {
    name: string;
    address: string;
    phone?: string;
    email?: string;
    currency?: string; // Currency code (e.g., 'INR', 'USD')
  };

  // Landlord information
  landlord: {
    name: string;
    phone?: string;
    email?: string;
  };

  // Tenant information
  tenant: {
    name: string;
    phone?: string;
    email?: string;
    address?: string;
  };

  // Receipt details
  receiptNumber: string;
  receiptDate: string; // ISO string
  period: {
    from: string; // ISO string
    to: string; // ISO string
  };

  // Financial breakdown
  breakdown: {
    baseRent: number;
    previousBalance: number;
    expenses: Array<{
      type: string;
      description: string;
      amount: number;
    }>;
    totalAmount: number;
    amountPaid: number;
    newBalance: number;
  };

  // Payment information
  payment: {
    method?: string;
    transactionId?: string;
    paidDate?: string; // ISO string
  };

  // Receipt settings (for customization)
  settings: {
    logoUrl?: string;
    bankDetails?: {
      bankName?: string;
      accountNumber?: string;
      ifscCode?: string;
      accountHolderName?: string;
    };
    wallets?: Array<{
      type: string;
      number: string;
      name: string;
    }>;
    upiId?: string;
    qrCodeUrl?: string;
    signatureUrl?: string;
    watermarkUrl?: string;
  };

  // Additional notes
  notes?: string;
  termsAndConditions?: string;

  // Watermark settings
  watermarkText?: string;
  isInvoice?: boolean;
}

export interface ReceiptInput {
  propertyId: string;
  rentTransactionId?: string;
  tenantId?: string;

  // Receipt details
  receiptDate: Date;
  amount: number;
  description: string;

  // Receipt content
  receiptData: ReceiptData;

  // Status
  status?: ReceiptStatus;

  // Generated by
  generatedBy: string;
}

export interface ReceiptGenerationRequest {
  paymentId: string;
  customSettings?: Partial<ReceiptData['settings']>;
  notes?: string;
}

export interface BulkReceiptGenerationRequest {
  propertyId: string;
  month: number; // 1-12
  year: number;
  includeAllTenants?: boolean;
  tenantIds?: string[]; // If not includeAllTenants, specify which tenants
}