// Database table names and column names
export const TABLES = {
  PROPERTIES: 'properties',
  TENANTS: 'tenants',
  LEASES: 'leases',
  RENT_PAYMENTS: 'rent_payments',
  TENANT_DOCUMENTS: 'tenant_documents',
  USERS: 'users',
} as const;

export const COLUMNS = {
  PROPERTIES: {
    ID: 'id',
    NAME: 'name',
    DESCRIPTION: 'description',
    PROPERTY_TYPE: 'property_type',
    STATUS: 'status',
    ADDRESS_STREET: 'address_street',
    ADDRESS_CITY: 'address_city',
    ADDRESS_STATE: 'address_state',
    ADDRESS_PINCODE: 'address_pincode',
    ADDRESS_LANDMARK: 'address_landmark',
    AREA: 'area',
    BEDROOMS: 'bedrooms',
    BATHROOMS: 'bathrooms',
    BALCONIES: 'balconies',
    FLOOR: 'floor',
    TOTAL_FLOORS: 'total_floors',
    AMENITIES: 'amenities',
    FURNISHED: 'furnished',
    PARKING_SPACES: 'parking_spaces',
    MONTHLY_RENT: 'monthly_rent',
    SECURITY_DEPOSIT: 'security_deposit',
    MAINTENANCE_CHARGES: 'maintenance_charges',
    OWNER_ID: 'owner_id',
    CO_OWNERS: 'co_owners',
    PHOTOS: 'photos',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TENANTS: {
    ID: 'id',
    FIRST_NAME: 'first_name',
    LAST_NAME: 'last_name',
    EMAIL: 'email',
    PHONE: 'phone',
    ALTERNATE_PHONE: 'alternate_phone',
    DATE_OF_BIRTH: 'date_of_birth',
    GENDER: 'gender',
    OCCUPATION: 'occupation',
    COMPANY_NAME: 'company_name',
    MONTHLY_INCOME: 'monthly_income',
    CURRENT_ADDRESS_STREET: 'current_address_street',
    CURRENT_ADDRESS_CITY: 'current_address_city',
    CURRENT_ADDRESS_STATE: 'current_address_state',
    CURRENT_ADDRESS_PINCODE: 'current_address_pincode',
    PERMANENT_ADDRESS_STREET: 'permanent_address_street',
    PERMANENT_ADDRESS_CITY: 'permanent_address_city',
    PERMANENT_ADDRESS_STATE: 'permanent_address_state',
    PERMANENT_ADDRESS_PINCODE: 'permanent_address_pincode',
    EMERGENCY_CONTACT_NAME: 'emergency_contact_name',
    EMERGENCY_CONTACT_RELATIONSHIP: 'emergency_contact_relationship',
    EMERGENCY_CONTACT_PHONE: 'emergency_contact_phone',
    STATUS: 'status',
    TOTAL_RENTALS: 'total_rentals',
    CURRENT_PROPERTY_ID: 'current_property_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TENANT_DOCUMENTS: {
    ID: 'id',
    TENANT_ID: 'tenant_id',
    DOCUMENT_TYPE: 'document_type',
    DOCUMENT_NUMBER: 'document_number',
    FILE_URL: 'file_url',
    VERIFIED: 'verified',
    VERIFIED_AT: 'verified_at',
    VERIFIED_BY: 'verified_by',
    UPLOADED_AT: 'uploaded_at',
  },
  LEASES: {
    ID: 'id',
    PROPERTY_ID: 'property_id',
    TENANT_ID: 'tenant_id',
    START_DATE: 'start_date',
    END_DATE: 'end_date',
    NOTICE_PERIOD_DAYS: 'notice_period_days',
    AUTO_RENEWAL: 'auto_renewal',
    MONTHLY_RENT: 'monthly_rent',
    SECURITY_DEPOSIT: 'security_deposit',
    MAINTENANCE_CHARGES: 'maintenance_charges',
    PAYMENT_FREQUENCY: 'payment_frequency',
    RENT_DUE_DAY: 'rent_due_day',
    ELECTRICITY_CHARGES: 'electricity_charges',
    WATER_CHARGES: 'water_charges',
    OTHER_CHARGES: 'other_charges',
    PETS_ALLOWED: 'pets_allowed',
    SMOKING_ALLOWED: 'smoking_allowed',
    SUBLETTING_ALLOWED: 'subletting_allowed',
    SPECIAL_CONDITIONS: 'special_conditions',
    STATUS: 'status',
    SIGNED_AT: 'signed_at',
    TERMINATED_AT: 'terminated_at',
    TERMINATION_REASON: 'termination_reason',
    LEASE_DOCUMENT_URL: 'lease_document_url',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  RENT_PAYMENTS: {
    ID: 'id',
    LEASE_ID: 'lease_id',
    PROPERTY_ID: 'property_id',
    TENANT_ID: 'tenant_id',
    AMOUNT: 'amount',
    DUE_DATE: 'due_date',
    PAID_DATE: 'paid_date',
    STATUS: 'status',
    PAYMENT_METHOD: 'payment_method',
    TRANSACTION_ID: 'transaction_id',
    PAYMENT_REFERENCE: 'payment_reference',
    LATE_FEE: 'late_fee',
    PENALTY_AMOUNT: 'penalty_amount',
    RENT_AMOUNT: 'rent_amount',
    MAINTENANCE_CHARGES: 'maintenance_charges',
    OTHER_CHARGES: 'other_charges',
    NOTES: 'notes',
    CREATED_BY: 'created_by',
    UPDATED_BY: 'updated_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USERS: {
    ID: 'id',
    USERNAME: 'username',
    EMAIL: 'email',
    PASSWORD: 'password',
    PHONE: 'phone',
    ROLE: 'role',
    IS_EMAIL_VERIFIED: 'is_email_verified',
    IS_PHONE_VERIFIED: 'is_phone_verified',
    EMAIL_VERIFICATION_TOKEN: 'email_verification_token',
    EMAIL_VERIFICATION_EXPIRES: 'email_verification_expires',
    PASSWORD_RESET_TOKEN: 'password_reset_token',
    PASSWORD_RESET_EXPIRES: 'password_reset_expires',
    GOOGLE_ID: 'google_id',
    PROFILE_PICTURE: 'profile_picture',
    LAST_LOGIN: 'last_login',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
} as const;

// User roles
export const USER_ROLES = {
  ADMIN: 'admin',
  USER: 'user',
} as const;

// Default values
export const DEFAULTS = {
  USER_ROLE: USER_ROLES.USER,
  PASSWORD_SALT_ROUNDS: 10,
} as const;